### ISSUE TITLE
No need to unwrap object

### ISSUE THREAD

**Issue by john-terenzio** [matt2tech/mattLipseyWebRentalAgency#1]
https://github.com/matt2tech/mattLipseyWebRentalAgency/blob/c5655e7cf563e02ff0c361f053f190b57fdf0b2d/javascript.js#L56-L62

Instead of creating a new object with the exact same keys as `data[mattress]` consider passing `data[mattress]` directly to template: `var html = template(data[mattress]);`.

**Comment by matt2tech** [comment]
Ah, good point. Since I'm using a for loop, I wouldn't have to build it again.
